# Site Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # Options: "air", "aqua", "contrast", "dirt", "sunrise"

# Site Information
title: "Data Portfolio"
name: "Anmol Bhatnagar"
description: "Data Scientist | Data Insights & Data Storytelling"
url: "https://username.github.io"
baseurl: ""

# Author Profile (This fills the left sidebar)
author:
  name: "Anmol Bhatnagar"
  bio: "Senior Income Analyst | SQL & Python Enthusiast"
  location: "Toronto, ON"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/anmol--bhatnagar/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AflameB"

# Performance/Jekyll Settings
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

include: ["_pages"]
